#!/usr/bin/env bash

if
  [[ -s "/home/maksim/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/environment" ]]
then
  source "/home/maksim/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/environment"
  exec gem "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/maksim/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/environment'" >&2
  exit 1
fi
