#!/usr/bin/env bash

if
  [[ -s "/home/maksim/.rvm/gems/ruby-2.7.0-preview1/environment" ]]
then
  source "/home/maksim/.rvm/gems/ruby-2.7.0-preview1/environment"
  exec ri "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/maksim/.rvm/gems/ruby-2.7.0-preview1/environment'" >&2
  exit 1
fi
